export const symbolToName: { [key: string]: string } = {
  btc: "bitcoin",
  eth: "ethereum",
  ltc: "litecoin",
  doge: "dogecoin",
  sol: "solana",
  xrp: "ripple",
  bnb: "binancecoin",
  matic: "polygon",
  ada: "cardano",
  dot: "polkadot",
  avax: "avalanche",
  link: "chainlink",
  uni: "uniswap",
  trx: "tron",
};

export const nameToSymbol: { [key: string]: string } = {
  bitcoin: "btc",
  ethereum: "eth",
  litecoin: "ltc",
  dogecoin: "doge",
  solana: "sol",
  ripple: "xrp",
  binancecoin: "bnb",
  polygon: "matic",
  cardano: "ada",
  polkadot: "dot",
  avalanche: "avax",
  chainlink: "link",
  uniswap: "uni",
  tron: "trx",
};
